name: mon_app
environment:
  sdk: '^3.10.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.5
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
